language: crystal

jobs:
  include:
    - stage: test
      before_script: mv .env.example .env
      script: crystal spec
    - stage: docs
      script: crystal doc

deploy:
  local_dir: doc
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
